---
title: "Analysis of single-cell RNA-seq data"
author:
  - name: Axel Klenk
    affiliation: Dept. of Medicine and Life Sciences, Universitat Pompeu Fabra, Barcelona
    email: axelvolker.klenk@upf.edu
  - name: Robert Castelo
    affiliation: Dept. of Medicine and Life Sciences, Universitat Pompeu Fabra, Barcelona
    email: robert.castelo@upf.edu
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analysis of single-cell RNA-seq data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Importing scRNA-seq data into a `SingleCellExperiment` object

```{r, message=FALSE}
library(TENxPBMCData)

sce <- TENxPBMCData(dataset="pbmc4k")
sce
```

# Importing gene sets

```{r}
library(GSVA)

fname <- "PBMC_gene_sets_TrianaEtAl2021.gmt"
gsets <- readGMT(system.file("extdata", fname, package="GSVAEuroBioC2024"))

```
# How to run GSVA

# Session information

```{r}
sessionInfo()
```

# References
